package CarRentalSystem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class MainMenuStudent extends javax.swing.JFrame {

    private static String MatricID;
    
    /**
     * Creates new form MainPage
     */
    public MainMenuStudent() {
        initComponents();
    }
    public static void setMatricID(String MatricID){
        MainMenuStudent.MatricID=MatricID;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        AddRental = new javax.swing.JButton();
        DeleteRental = new javax.swing.JButton();
        UpdateRental = new javax.swing.JButton();
        Personal = new javax.swing.JButton();
        ViewRental = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Availability = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(775, 440));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Car Rental System Menu");

        AddRental.setText("Add A Rental Car");
        AddRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRentalActionPerformed(evt);
            }
        });

        DeleteRental.setText("Delete A Rental Car");
        DeleteRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRentalActionPerformed(evt);
            }
        });

        UpdateRental.setText("Update A Rental Car");
        UpdateRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRentalActionPerformed(evt);
            }
        });

        Personal.setText("Personal Details");
        Personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalActionPerformed(evt);
            }
        });

        ViewRental.setText("View Car Rental Details");
        ViewRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRentalActionPerformed(evt);
            }
        });

        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Availability.setText("View Car Availability");
        Availability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvailabilityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ViewRental, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(Availability, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddRental, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeleteRental, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateRental, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Personal, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateRental, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Availability, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteRental, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddRental, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Personal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewRental, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRentalActionPerformed
        // TODO add your handling code here:
        AddRentalCar AddRental=new AddRentalCar();
        AddRental.setDefaultCloseOperation(AddRentalCar.DISPOSE_ON_CLOSE);
        this.setVisible(false);
        AddRental.setVisible(true);
    }//GEN-LAST:event_AddRentalActionPerformed

    private void DeleteRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRentalActionPerformed
        // TODO add your handling code here:
        DeleteRentalCar DeleteRental=new DeleteRentalCar();
        DeleteRental.setDefaultCloseOperation(DeleteRentalCar.DISPOSE_ON_CLOSE);
        this.setVisible(false);
        DeleteRental.setVisible(true);
    }//GEN-LAST:event_DeleteRentalActionPerformed

    private void UpdateRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRentalActionPerformed
        // TODO add your handling code here:
        UpdateRentalCar UpdateRental=new UpdateRentalCar();
        UpdateRental.setDefaultCloseOperation(UpdateRentalCar.DISPOSE_ON_CLOSE);
        this.setVisible(false);
        UpdateRental.setVisible(true);
    }//GEN-LAST:event_UpdateRentalActionPerformed

    private void ViewRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRentalActionPerformed
        // TODO add your handling code here:
        ViewRentalCarDetails ViewRental=new ViewRentalCarDetails();
        ViewRental.setDefaultCloseOperation(UpdateRentalCar.DISPOSE_ON_CLOSE);
        this.setVisible(false);
        ViewRental.setVisible(true);
    }//GEN-LAST:event_ViewRentalActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        LogOut logout=new LogOut();
        logout.setDefaultCloseOperation(LogOut.DISPOSE_ON_CLOSE);
        this.setVisible(false);
        logout.setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void AvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvailabilityActionPerformed
        // TODO add your handling code here:
        ViewCarModel carModel=new ViewCarModel();
        carModel.setDefaultCloseOperation(ViewCarModel.DISPOSE_ON_CLOSE);
        this.setVisible(false);
        carModel.setVisible(true);
    }//GEN-LAST:event_AvailabilityActionPerformed

    private void PersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalActionPerformed
        // TODO add your handling code here:
        PersonalDetails personaldetails=new PersonalDetails();
        PersonalDetails.setMatricID(MatricID);
        personaldetails.setDefaultCloseOperation(PersonalDetails.DISPOSE_ON_CLOSE);
        this.setVisible(false);
        personaldetails.setVisible(true);
    }//GEN-LAST:event_PersonalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRental;
    private javax.swing.JButton Availability;
    private javax.swing.JButton DeleteRental;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Personal;
    private javax.swing.JButton UpdateRental;
    private javax.swing.JButton ViewRental;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
